//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessObjectsLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CouponHubDBEntities : DbContext
    {
        public CouponHubDBEntities()
            : base("name=CouponHubDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_Table> Category_Table { get; set; }
        public virtual DbSet<Url_Table> Url_Table { get; set; }
        public virtual DbSet<User_Table> User_Table { get; set; }
    }
}
