//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessObjectsLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Url_Table
    {
        public int UrlId { get; set; }
        public string UrlTitle { get; set; }
        public string Url { get; set; }
        public string UrlDesc { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IsApproved { get; set; }
        public string Coupon { get; set; }
    
        public virtual Category_Table Category_Table { get; set; }
        public virtual User_Table User_Table { get; set; }
    }
}
